# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy", "pillow"]
# ///
"""The demo's ring field, whole and unresampled, as a flash asset.

The original scrolls a 320x200 window around a 640x400 image while cycling the
palette. We do the same with a 240x240 window, so the field is stored at its
native size and every pixel is the demo's own — no scaling, no interpolation
across the sawtooth's wrap.
"""
import numpy as np
from PIL import Image

SRC = r"D:\source\psycho\work\assets\003_rings_640x400.png"
FW, FH, WIN = 640, 400, 240
idx = np.array(Image.open(SRC))
assert idx.shape == (FH, FW), idx.shape
lo, hi = int(idx.min()), int(idx.max())
field = ((idx.astype(np.int32) - lo) * 128 // (hi - lo + 1)).astype(np.uint8) & 0x7F
print(f"{FW}x{FH}, source indices {lo}..{hi} -> bank 0..{field.max()}")
print(f"window {WIN}x{WIN}: scroll room {FW - WIN} x {FH - WIN} px")

stops = [(0, (0, 0, 0)), (26, (72, 0, 0)), (58, (196, 8, 0)), (84, (252, 56, 16)),
         (108, (150, 10, 0)), (127, (0, 0, 0))]
pal = np.zeros((128, 3), np.uint8)
for (a0, c0), (a1, c1) in zip(stops, stops[1:]):
    for i in range(a0, a1 + 1):
        f = (i - a0) / max(a1 - a0, 1)
        pal[i] = [int(c0[k] + (c1[k] - c0[k]) * f) for k in range(3)]

# three windows at different scroll offsets and palette phases, as the panel sees them
sheet = Image.new("RGB", (WIN * 3 + 16, WIN), (20, 20, 20))
for n, (ox, oy, ph) in enumerate([(0, 0, 0), (200, 80, 40), (380, 150, 90)]):
    win = (field[oy:oy + WIN, ox:ox + WIN] + ph) & 0x7F
    sheet.paste(Image.fromarray(pal[win], "RGB"), (n * (WIN + 8), 0))
sheet.save("rings_window_preview.png")

with open("rings_field.cpp", "w", encoding="utf-8") as fh:
    fh.write("// Generated by scripts/make_rings_field.py - do not edit.\n")
    fh.write('#include "rings_field.h"\n\n')
    fh.write(f"const uint8_t RINGS_FIELD[{FH} * {FW}] = {{\n")
    flat = field.reshape(-1)
    for i in range(0, flat.size, 24):
        fh.write("    " + ",".join(f"{v:3d}" for v in flat[i:i + 24]) + ",\n")
    fh.write("};\n")
print("wrote rings_window_preview.png and rings_field.cpp")
