# /// script
# requires-python = ">=3.11"
# dependencies = ["numpy", "pillow"]
# ///
r"""Emit the tunnel's field AND its palette as smolbase flash assets.

Both come from the reconstruction in D:\source\psycho: the 640x400 index
field (the demo's own artwork) and the three 225-byte channel tables from
src/gen/P3PAL.INC. Nothing is rescaled — the indices are the demo's, and the
palette is 6-bit VGA exactly as the DAC received it.
"""
import re
import numpy as np
from PIL import Image

SRC_IMG = r"D:\source\psycho\assets\part003\tunnel_640x400.png"
SRC_PAL = r"D:\source\psycho\src\gen\P3PAL.INC"
FW, FH = 640, 400

field = np.array(Image.open(SRC_IMG))
assert field.shape == (FH, FW), field.shape
print(f"field {FW}x{FH}, indices {field.min()}..{field.max()}")

text = open(SRC_PAL, encoding="utf-8", errors="replace").read()
tables = {}
for name in ("Red", "Green", "Blue"):
    m = re.search(name + r"\s*:\s*TColourTable\s*=\s*\((.*?)\)\s*;", text, re.S)
    vals = [int(v) for v in re.findall(r"-?\d+", m.group(1))]
    assert len(vals) == 225, (name, len(vals))
    tables[name] = vals
    print(f"{name:5s} 225 entries, max {max(vals)} (6-bit VGA)")

# The glyph hiding in the palette: 15 bands x 15 entries, printed as a bitmap.
print("\nthe palette IS a 15x15 tile — nonzero red:")
for band in range(15):
    row = tables["Red"][band * 15:(band + 1) * 15]
    print("   " + "".join("#" if v else "." for v in row))

with open("rings_field.cpp", "w", encoding="utf-8") as fh:
    fh.write("// Generated by scripts/make_rings_field.py - do not edit.\n")
    fh.write('#include "rings_field.h"\n\n')
    fh.write(f"const uint8_t RINGS_FIELD[{FH} * {FW}] = {{\n")
    flat = field.reshape(-1)
    for i in range(0, flat.size, 24):
        fh.write("    " + ",".join(f"{v:3d}" for v in flat[i:i + 24]) + ",\n")
    fh.write("};\n\n")
    for name, key in (("RINGS_RED", "Red"), ("RINGS_GREEN", "Green"), ("RINGS_BLUE", "Blue")):
        fh.write(f"const uint8_t {name}[RINGS_COLOURS] = {{\n")
        v = tables[key]
        for i in range(0, 225, 15):
            fh.write("    " + ",".join(f"{x:2d}" for x in v[i:i + 15]) + ",\n")
        fh.write("};\n\n")
print("\nwrote rings_field.cpp")
